// This file is generated by icon spritesheet generator

export const iconNames = [
  "building-2",
  "check",
  "chevron-down",
  "chevron-up",
  "download",
  "facebook",
  "globe",
  "instagram",
  "link",
  "linkedin",
  "mail",
  "map-pin",
  "message-circle",
  "phone",
  "smartphone",
  "user",
] as const

export type IconName = typeof iconNames[number]
